version: '3'

services:

#################### WORDPRESS ####################

  wp:
    depends_on:
      - mysql
    image: wordpress:php7.4-apache
    container_name: ${NAME}-wp
    volumes:
      - ${RUTA}/${NAME}-wp:/var/www/html
      - ${RUTA}/etcwp:/etc/wordpress
      - ${RUTA}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M    
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: ${NAME}-mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser-${NAME}
      WORDPRESS_DB_PASSWORD: ""
    networks:
      - traefik_net
    labels:
      - "traefik.http.routers.${NAME}-wp.rule=Host(`${DOMAIN}`, `www.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.middlewares=${NAME}-redirect"
      - "traefik.http.routers.${NAME}-wp.service=wp-${NAME}@docker"
      - "traefik.http.routers.${NAME}-wp.entrypoints=https"
      - "traefik.http.routers.${NAME}-wp.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.${NAME}-wp.tls=true"
      - "traefik.http.middlewares.${NAME}-wp.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${NAME}-wp.redirectscheme.permanent=true"
      - "traefik.http.middlewares.${NAME}-wp.redirectscheme.port=443"
      - "traefik.http.middlewares.${NAME}-redirect.headers.SSLForceHost=true"
      - "traefik.http.middlewares.${NAME}-redirect.headers.SSLHost=${DOMAIN}"      

#################### FIN WORDPRESS ####################


#################### DATA BASE ####################

  mysql:
    image: mysql:8.0
    container_name: ${NAME}-mysql
    volumes:
      - ${RUTA}/${NAME}-mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M     
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser-${NAME}
      MYSQL_PASSWORD: ""
    networks:
      - traefik_net
    labels:
      - "traefik.tcp.routers.mysql-${NAME}.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql-${NAME}.entrypoints=mysql"
      - "traefik.tcp.routers.mysql-${NAME}.service=mysql-${NAME}"
      - "traefik.tcp.services.mysql-${NAME}.loadbalancer.server.port=3306"


#################### FIN DATA BASE ####################

networks:
  traefik_net:
    external: true



